name: Dependabot Schedule

# Checks every day at 4.30 a.m.
on:
  schedule:
    - cron: '30 4 * * *'

jobs:
  dependabot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run UpGradle
        uses: DanySK/upgradle-action@master
        with:
          token: ${{ secrets.DEP_TOKEN }}
          configuration_file: upgradle.yml
          version: 0.3.4
